<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472;net480;net6.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <Version>1.0.53</Version>
		<LangVersion>preview</LangVersion>
  </PropertyGroup>
	<PropertyGroup>

  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ProductionStackTrace\BuilderProxy.cs" Link="BuilderProxy.cs" />
    <Compile Include="..\ProductionStackTrace\ExceptionEx.cs" Link="ExceptionEx.cs" />
    <Compile Include="..\ProductionStackTrace\ExceptionReporting.cs" Link="ExceptionReporting.cs" />
    <Compile Include="..\ProductionStackTrace\Internals\AssemblyDebugInfo.cs" Link="Internals\AssemblyDebugInfo.cs" />
    <Compile Include="..\ProductionStackTrace\Internals\PeHeaders.cs" Link="Internals\PeHeaders.cs" />
    <Compile Include="..\ProductionStackTrace\LogClasses.cs" Link="LogClasses.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Internals\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Pillar.Demystifier\src\Pillar.Demystifier\Pillar.Demystifier.csproj" />
  </ItemGroup>

</Project>
