<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net472' or '$(TargetFramework)' == 'net480'">
    <ReflectionMetadataFiles Include="$(MSBuildThisFileDirectory)System.Reflection.Metadata.dll" />
    <None Include="@(ReflectionMetadataFiles)" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>
</Project>
