<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>preview</LangVersion>
		<ApplicationIcon>icon.png.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="icon.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="icon.png.ico" />
		<Resource Include="icon.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EasyWindowsTerminalControl" Version="1.0.36" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ProductionStackTrace.Analyze.Console\ProductionStackTrace.Analyze.Console.csproj" />
	</ItemGroup>

</Project>
