<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>bin\$(Configuration)\$(TargetFrameworkVersion)\</OutputPath>
    <PackageOutputDir>bin\$(Configuration)</PackageOutputDir>
    <DocumentationFile>$(OutputPath)\$(AssemblyName).xml</DocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
		<PackageReference Include="MoeDotKawayi.Pillar.Demystifier" Version="0.4.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />

  </ItemGroup>
</Project>