<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>bin\$(Configuration)\$(TargetFrameworkVersion)\</OutputPath>
    <PackageOutputDir>bin\$(Configuration)</PackageOutputDir>
    <DocumentationFile>$(OutputPath)\$(AssemblyName).xml</DocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ben.Demystifier">
      <Version>0.4.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Memory">
      <Version>4.5.5</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Metadata">
      <Version>6.0.1</Version>
    </PackageReference>
  </ItemGroup>
</Project>